name: "Gradle Build"
description: "gradle build and test"

inputs:
  blubber:
    description: “just sample”
    required: false
outputs:
  jar-version:
    description: "Jar version"
    value: ${{ steps.extract-version.outputs.version }}
    
runs:
  using: "composite"
  steps:
    

    - name: extract version
      id: extract-version
      shell: bash
      run: "echo ::set-output name=version::$( ./gradlew properties | sed -n -e 's/^version: \\(.*\\)$/\\1/p' )"
      

      
#    - uses: dorny/test-reporter@v1.5.0
#      with:
#        artifact: test-results              # artifact name
#        name: JUnit Tests                   # Name of the check run which will be created
#        path: build/test-results/test/*.xml # Path to test results (inside artifact .zip)
#        reporter: java-junit                # Format of test results
        
#    - run: ls -al build/test-results/test
#      shell: bash
      
#    - name: Publish Unit Test Results
#      uses: EnricoMi/publish-unit-test-result-action@v1.19
##      if: always()
#      with:
#        files: build/test-results/test/*.xml
