name: "Gradle Build"
description: "gradle build and test"

inputs:
  blubber:
    description: “just sample”
    required: false
outputs:
  jar-version:
    description: "Jar version"
    value: ${{ steps.extract-version.outputs.version }}
    
runs:
  using: "composite"
  steps:
   - uses: actions/checkout@v2
   
   - name: Set up JDK 11
     uses: actions/setup-java@v2
     with:
       java-version: '11'
       distribution: 'adopt'

   - name: Cache Gradle packages
     uses: actions/cache@v2
     with:
       path: |
         ~/.gradle/caches
         ~/.gradle/wrapper
       key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
       restore-keys: |
         ${{ runner.os }}-gradle-
          
   - name: Grant execute permission for gradlew
     shell: bash
     run: chmod +x gradlew

   - name: Build with Gradle
     shell: bash
     run: ./gradlew --info -Pversion=2.0 cleanTest build

   - name: extract version
     id: extract-version
     shell: bash
     run: "echo ::set-output name=version::$( ./gradlew properties | sed -n -e 's/^version: \\(.*\\)$/\\1/p' )"

   - run: ls -al build/test-results/test
     shell: bash
    
   - name: Publish Unit Test Results
     uses: EnricoMi/publish-unit-test-result-action@v1.19
#     if: always()
     with:
       files: build/test-results/test/*.xml
      

